env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2015
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  quotes:
    - warn
    - single
  comma-dangle:
    - error
    - always-multiline
  no-extra-semi: warn
  no-inferrable-types: off
  '@typescript-eslint/no-non-null-assertion': off
